#!/usr/bin/env bash
# Script to configure HAProxy for SSL termination

DOMAIN="www.phillip-mulindwa.tech"
CERT_DIR="/etc/haproxy/certs"
LB_SERVER="lb-01"
EMAIL="p.mulindwa@alustudent.com"

# Install HAProxy and Certbot
echo "Installing HAProxy and Certbot..."
sudo apt-get update
sudo apt-get install -y haproxy certbot

# Create directory for SSL certificates if it doesn't exist
sudo mkdir -p $CERT_DIR

# Obtain SSL certificate
echo "Obtaining SSL certificate..."
sudo certbot certonly --standalone -d $DOMAIN --non-interactive --agree-tos --email $EMAIL

# Combine SSL certificate and key
echo "Combining SSL certificate and key..."
sudo cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem | sudo tee $CERT_DIR/$DOMAIN.pem

# Configure HAProxy
echo "Configuring HAProxy..."
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL settings
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend lb-frontend
    bind *:80
    reqadd X-Forwarded-Proto:\ http
    default_backend lb-backend

frontend lb-frontend-https
    bind *:443 ssl crt $CERT_DIR/$DOMAIN.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend lb-backend

backend lb-backend
    balance roundrobin
    server web-01 44.203.4.64:80 check
    server web-02 3.84.43.231:80 check
EOF

# Restart HAProxy
echo "Restarting HAProxy..."
sudo service restart haproxy
sudo serrvice enable haproxy

echo "HAProxy SSL termination setup complete."
