#!/usr/bin/env bash
# Script to configure HAProxy backend servers for load balancing

DOMAIN="www.twosandfours.tech"
CERT_DIR="/etc/haproxy/certs"
LB_SERVER="lb-01"
EMAIL="b.gatanazi@alustudent.com"

# Install HAProxy
echo "Installing HAProxy..."
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy backend servers
echo "Configuring HAProxy backend servers..."
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend lb-frontend
    bind *:80
    reqadd X-Forwarded-Proto:\ http
    default_backend lb-backend

frontend lb-frontend-https
    bind *:443 ssl crt $CERT_DIR/$DOMAIN.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend lb-backend

# Backend load balancing configuration
backend lb-backend
    balance roundrobin
    server web-01 44.204.52.216:80 check
    server web-02 3.86.245.222:80 check
EOF

# Restart HAProxy service
echo "Restarting HAProxy..."
sudo service restart haproxy
sudo service enable haproxy

echo "Backend server and load balancing configuration complete."
